package com.cloudminds.meta.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cloudminds.meta.bean.FamilyItemBean;

import com.cloudminds.meta.greendao.FamilyItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig familyItemBeanDaoConfig;

    private final FamilyItemBeanDao familyItemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        familyItemBeanDaoConfig = daoConfigMap.get(FamilyItemBeanDao.class).clone();
        familyItemBeanDaoConfig.initIdentityScope(type);

        familyItemBeanDao = new FamilyItemBeanDao(familyItemBeanDaoConfig, this);

        registerDao(FamilyItemBean.class, familyItemBeanDao);
    }
    
    public void clear() {
        familyItemBeanDaoConfig.clearIdentityScope();
    }

    public FamilyItemBeanDao getFamilyItemBeanDao() {
        return familyItemBeanDao;
    }

}
