package com.example.wqllj.locationshare.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baidu.mapapi.model.LatLng;
import com.example.wqllj.locationshare.db.converter.StringConverterLatLng;

import com.example.wqllj.locationshare.db.bean.CoordinatePointBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COORDINATE_POINT_BEAN".
*/
public class CoordinatePointBeanDao extends AbstractDao<CoordinatePointBean, Long> {

    public static final String TABLENAME = "COORDINATE_POINT_BEAN";

    /**
     * Properties of entity CoordinatePointBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LatLng = new Property(1, String.class, "latLng", false, "LAT_LNG");
        public final static Property RouteLineId = new Property(2, Long.class, "routeLineId", false, "ROUTE_LINE_ID");
        public final static Property Date = new Property(3, Long.class, "date", false, "DATE");
    }

    private final StringConverterLatLng latLngConverter = new StringConverterLatLng();

    public CoordinatePointBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CoordinatePointBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COORDINATE_POINT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LAT_LNG\" TEXT," + // 1: latLng
                "\"ROUTE_LINE_ID\" INTEGER," + // 2: routeLineId
                "\"DATE\" INTEGER);"); // 3: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COORDINATE_POINT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CoordinatePointBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        LatLng latLng = entity.getLatLng();
        if (latLng != null) {
            stmt.bindString(2, latLngConverter.convertToDatabaseValue(latLng));
        }
 
        Long routeLineId = entity.getRouteLineId();
        if (routeLineId != null) {
            stmt.bindLong(3, routeLineId);
        }
 
        Long date = entity.getDate();
        if (date != null) {
            stmt.bindLong(4, date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CoordinatePointBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        LatLng latLng = entity.getLatLng();
        if (latLng != null) {
            stmt.bindString(2, latLngConverter.convertToDatabaseValue(latLng));
        }
 
        Long routeLineId = entity.getRouteLineId();
        if (routeLineId != null) {
            stmt.bindLong(3, routeLineId);
        }
 
        Long date = entity.getDate();
        if (date != null) {
            stmt.bindLong(4, date);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CoordinatePointBean readEntity(Cursor cursor, int offset) {
        CoordinatePointBean entity = new CoordinatePointBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : latLngConverter.convertToEntityProperty(cursor.getString(offset + 1)), // latLng
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // routeLineId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CoordinatePointBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLatLng(cursor.isNull(offset + 1) ? null : latLngConverter.convertToEntityProperty(cursor.getString(offset + 1)));
        entity.setRouteLineId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CoordinatePointBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CoordinatePointBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CoordinatePointBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
