package com.example.wqllj.locationshare.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.wqllj.locationshare.db.bean.CoordinatePointBean;

import com.example.wqllj.locationshare.db.bean.EventBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EVENT_BEAN".
*/
public class EventBeanDao extends AbstractDao<EventBean, Long> {

    public static final String TABLENAME = "EVENT_BEAN";

    /**
     * Properties of entity EventBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Action = new Property(2, int.class, "action", false, "ACTION");
        public final static Property Data = new Property(3, String.class, "data", false, "DATA");
        public final static Property Person_id = new Property(4, Long.class, "person_id", false, "PERSON_ID");
        public final static Property CoordinatePointId = new Property(5, Long.class, "coordinatePointId", false, "COORDINATE_POINT_ID");
    }

    private DaoSession daoSession;


    public EventBeanDao(DaoConfig config) {
        super(config);
    }
    
    public EventBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EVENT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ACTION\" INTEGER NOT NULL ," + // 2: action
                "\"DATA\" TEXT," + // 3: data
                "\"PERSON_ID\" INTEGER," + // 4: person_id
                "\"COORDINATE_POINT_ID\" INTEGER);"); // 5: coordinatePointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EVENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EventBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getAction());
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(4, data);
        }
 
        Long person_id = entity.getPerson_id();
        if (person_id != null) {
            stmt.bindLong(5, person_id);
        }
 
        Long coordinatePointId = entity.getCoordinatePointId();
        if (coordinatePointId != null) {
            stmt.bindLong(6, coordinatePointId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EventBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getAction());
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(4, data);
        }
 
        Long person_id = entity.getPerson_id();
        if (person_id != null) {
            stmt.bindLong(5, person_id);
        }
 
        Long coordinatePointId = entity.getCoordinatePointId();
        if (coordinatePointId != null) {
            stmt.bindLong(6, coordinatePointId);
        }
    }

    @Override
    protected final void attachEntity(EventBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EventBean readEntity(Cursor cursor, int offset) {
        EventBean entity = new EventBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // action
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // data
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // person_id
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // coordinatePointId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EventBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAction(cursor.getInt(offset + 2));
        entity.setData(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPerson_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setCoordinatePointId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EventBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EventBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EventBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCoordinatePointBeanDao().getAllColumns());
            builder.append(" FROM EVENT_BEAN T");
            builder.append(" LEFT JOIN COORDINATE_POINT_BEAN T0 ON T.\"COORDINATE_POINT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected EventBean loadCurrentDeep(Cursor cursor, boolean lock) {
        EventBean entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CoordinatePointBean pointBean = loadCurrentOther(daoSession.getCoordinatePointBeanDao(), cursor, offset);
        entity.setPointBean(pointBean);

        return entity;    
    }

    public EventBean loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<EventBean> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<EventBean> list = new ArrayList<EventBean>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<EventBean> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<EventBean> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
